#######################################################################
#  ████████▄     ▄████████    ▄████████    ▄████████    ▄█   ▄█▄      #
#  ███   ▀███   ███    ███   ███    ███   ███    ███   ███ ▄███▀      #
#  ███    ███   ███    ███   ███    █▀    ███    ███   ███▐██▀        #
#  ███    ███   ███    ███  ▄███▄▄▄      ▄███▄▄▄▄██▀  ▄█████▀         #
#  ███    ███ ▀███████████ ▀▀███▀▀▀       ███▀▀▀▀▀   ▀▀█████▄         #
#  ███    ███   ███    ███   ███    █▄   ▀██████████   ███▐██▄        #
#  ███   ▄███   ███    ███   ███    ███   ███    ███   ███ ▀███▄      #
#  ████████▀    ███    █▀    ██████████   ███    ███   ███   ▀█▀      #
#                                                                     #
#######################################################################

config:
## Here you can list the blocks that should be detected so that a player explodes when standing on one of them.
## DEFAULT: [GRASS_BLOCK]
## Add more entries to trigger on additional blocks, e.g. DIRT.
## Page containing information about blocks in Minecraft: https://minecraftitemids.com
  block_explode:
    blocks:
      - GRASS_BLOCK
